const neighborhoods = [
  {
    id: 1,
    name: "Bukchon Hanok Village",
    district: "Jongno-gu",
    description: "A living museum of traditional Korean architecture with hundreds of hanok houses dating back to the Joseon Dynasty.",
    tags: ["historic", "culture", "architecture", "photography"],
    image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=600&q=80",
    highlight: "Traditional hanok alleyways",
  },
  {
    id: 2,
    name: "Hongdae",
    district: "Mapo-gu",
    description: "Seoul's youth culture hub bursting with indie music, street art, quirky cafés, and a 24/7 party atmosphere near Hongik University.",
    tags: ["nightlife", "art", "music", "food", "shopping"],
    image: "https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=600&q=80",
    highlight: "Street performances on weekends",
  },
  {
    id: 3,
    name: "Insadong",
    district: "Jongno-gu",
    description: "A charming district known for its antique shops, traditional teahouses, and galleries showcasing Korean arts and crafts.",
    tags: ["culture", "art", "shopping", "historic"],
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=600&q=80",
    highlight: "Traditional tea ceremonies",
  },
  {
    id: 4,
    name: "Gangnam",
    district: "Gangnam-gu",
    description: "Seoul's most glamorous district with upscale boutiques, Michelin-starred restaurants, and the iconic COEX Mall.",
    tags: ["shopping", "food", "nightlife", "luxury"],
    image: "https://images.unsplash.com/photo-1517650862521-d580d5348145?w=600&q=80",
    highlight: "COEX Starfield Library",
  },
  {
    id: 5,
    name: "Itaewon",
    district: "Yongsan-gu",
    description: "Seoul's most cosmopolitan neighbourhood, offering global cuisine, vintage fashion, and a vibrant LGBTQ+ scene.",
    tags: ["food", "nightlife", "multicultural", "shopping"],
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80",
    highlight: "International food street",
  },
  {
    id: 6,
    name: "Myeongdong",
    district: "Jung-gu",
    description: "A bustling shopping mecca famous for K-beauty products, street food stalls, and a dazzling array of fashion brands.",
    tags: ["shopping", "food", "beauty", "tourist"],
    image: "https://images.unsplash.com/photo-1546874177-9e664107314e?w=600&q=80",
    highlight: "K-beauty shopping paradise",
  },
  {
    id: 7,
    name: "Seongsu-dong",
    district: "Seongdong-gu",
    description: "Seoul's 'Brooklyn' — a former industrial area transformed into a hotspot for artisan coffee, design studios, and pop-up stores.",
    tags: ["coffee", "art", "hipster", "food", "shopping"],
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    highlight: "Specialty coffee roasters",
  },
  {
    id: 8,
    name: "Gyeongbokgung Palace Area",
    district: "Jongno-gu",
    description: "Home to Seoul's grandest Joseon-era palace, the National Folk Museum, and the changing of the royal guard ceremony.",
    tags: ["historic", "culture", "architecture", "photography"],
    image: "https://images.unsplash.com/photo-1610649673776-f8bbe22fce9a?w=600&q=80",
    highlight: "Royal guard changing ceremony",
  },
  {
    id: 9,
    name: "Dongdaemun",
    district: "Jung-gu",
    description: "A fashion and design district that never sleeps, anchored by the futuristic Dongdaemun Design Plaza and sprawling wholesale markets.",
    tags: ["shopping", "fashion", "architecture", "nightlife"],
    image: "https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=600&q=80",
    highlight: "DDP — open 24 hours",
  },
  {
    id: 10,
    name: "Mangwon",
    district: "Mapo-gu",
    description: "A laid-back residential neighborhood with a beloved weekend market, independent bookshops, and some of Seoul's best brunch spots.",
    tags: ["local", "food", "coffee", "market"],
    image: "https://images.unsplash.com/photo-1466442929976-97f336a657be?w=600&q=80",
    highlight: "Mangwon Market on weekends",
  },
];
